version: '3.6'

services:
  livraria.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
      - "44300:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on: 
      - livraria.db

  livraria.db:
    container_name: livraria.database
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: 
      - "11433:1433"
      - "136:135"
      - "51998:51999" 
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqldata:/var/opt/mssql
        
volumes:
  mssqldata: 